/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCXFILE_H_RPCGEN
#define _RPCXFILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_STANZA_LENGTH 10
#define MAX_UTENTI 4
#define MAX_NUM 3
#define MAX_NOME 8

struct Utente {
	char nome[MAX_NOME];
};
typedef struct Utente Utente;

struct Stanza {
	char nome[MAX_STANZA_LENGTH];
	char tipo;
	Utente utenti[MAX_UTENTI];
};
typedef struct Stanza Stanza;

struct Richiesta {
	char nome[MAX_STANZA_LENGTH];
	char tipo;
};
typedef struct Richiesta Richiesta;

struct Risultato {
	Stanza num[MAX_NUM];
	int esito;
};
typedef struct Risultato Risultato;

#define OPERATION 0x20000013
#define OPERATIONVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define aggiungi_stanza 1
extern  int * aggiungi_stanza_1(Richiesta *, CLIENT *);
extern  int * aggiungi_stanza_1_svc(Richiesta *, struct svc_req *);
#define elimina_utente 2
extern  Risultato * elimina_utente_1(char **, CLIENT *);
extern  Risultato * elimina_utente_1_svc(char **, struct svc_req *);
extern int operation_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define aggiungi_stanza 1
extern  int * aggiungi_stanza_1();
extern  int * aggiungi_stanza_1_svc();
#define elimina_utente 2
extern  Risultato * elimina_utente_1();
extern  Risultato * elimina_utente_1_svc();
extern int operation_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Utente (XDR *, Utente*);
extern  bool_t xdr_Stanza (XDR *, Stanza*);
extern  bool_t xdr_Richiesta (XDR *, Richiesta*);
extern  bool_t xdr_Risultato (XDR *, Risultato*);

#else /* K&R C */
extern bool_t xdr_Utente ();
extern bool_t xdr_Stanza ();
extern bool_t xdr_Richiesta ();
extern bool_t xdr_Risultato ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCXFILE_H_RPCGEN */
