/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCXFILE_H_RPCGEN
#define _RPCXFILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_GIORNO 10
#define MAX_PREVISIONE 10
#define MAX_GIORNI 8
#define MAX_AUDIO 256
#define MAX_BUFF 256

struct PrevedoBrutto {
	char giorno[MAX_GIORNO];
	char previsione[MAX_PREVISIONE];
	int max;
	int min;
	char fileAudio[MAX_AUDIO];
};
typedef struct PrevedoBrutto PrevedoBrutto;

struct Giorno {
	char giorno[MAX_GIORNO];
	int max;
	int min;
};
typedef struct Giorno Giorno;

struct Output {
	Giorno giorni[MAX_GIORNI];
	int dim;
};
typedef struct Output Output;

#define OPERATION 0x20000013
#define OPERATIONVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define visualizza_dati 1
extern  Output * visualizza_dati_1(char **, CLIENT *);
extern  Output * visualizza_dati_1_svc(char **, struct svc_req *);
#define aggiorna_temperature 2
extern  int * aggiorna_temperature_1(Giorno *, CLIENT *);
extern  int * aggiorna_temperature_1_svc(Giorno *, struct svc_req *);
extern int operation_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define visualizza_dati 1
extern  Output * visualizza_dati_1();
extern  Output * visualizza_dati_1_svc();
#define aggiorna_temperature 2
extern  int * aggiorna_temperature_1();
extern  int * aggiorna_temperature_1_svc();
extern int operation_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_PrevedoBrutto (XDR *, PrevedoBrutto*);
extern  bool_t xdr_Giorno (XDR *, Giorno*);
extern  bool_t xdr_Output (XDR *, Output*);

#else /* K&R C */
extern bool_t xdr_PrevedoBrutto ();
extern bool_t xdr_Giorno ();
extern bool_t xdr_Output ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCXFILE_H_RPCGEN */
