/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCXFILE_H_RPCGEN
#define _RPCXFILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_LENGTH_FILE 40
#define MAX_LENGTH 256
#define MAX_SONGS 6
#define N 12

struct Canzone {
	char cantante[MAX_LENGTH];
	char titolo[MAX_LENGTH];
	char nomeFile[MAX_LENGTH_FILE];
	int voti;
};
typedef struct Canzone Canzone;

struct Richiesta {
	char parametro[MAX_LENGTH];
	int Titolo_Cantante;
};
typedef struct Richiesta Richiesta;

struct Risultato {
	Canzone canzoni[MAX_SONGS];
	int dim;
};
typedef struct Risultato Risultato;

#define OPERATION 0x20000013
#define OPERATIONVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define visualizza_canzoni_conmenodi_v_voti 1
extern  Risultato * visualizza_canzoni_conmenodi_v_voti_1(int *, CLIENT *);
extern  Risultato * visualizza_canzoni_conmenodi_v_voti_1_svc(int *, struct svc_req *);
#define esprimi_voto 2
extern  int * esprimi_voto_1(Richiesta *, CLIENT *);
extern  int * esprimi_voto_1_svc(Richiesta *, struct svc_req *);
extern int operation_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define visualizza_canzoni_conmenodi_v_voti 1
extern  Risultato * visualizza_canzoni_conmenodi_v_voti_1();
extern  Risultato * visualizza_canzoni_conmenodi_v_voti_1_svc();
#define esprimi_voto 2
extern  int * esprimi_voto_1();
extern  int * esprimi_voto_1_svc();
extern int operation_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Canzone (XDR *, Canzone*);
extern  bool_t xdr_Richiesta (XDR *, Richiesta*);
extern  bool_t xdr_Risultato (XDR *, Risultato*);

#else /* K&R C */
extern bool_t xdr_Canzone ();
extern bool_t xdr_Richiesta ();
extern bool_t xdr_Risultato ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCXFILE_H_RPCGEN */
