/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RPCxFile.h"

bool_t
xdr_Canzone (XDR *xdrs, Canzone *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->cantante, MAX_LENGTH,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->titolo, MAX_LENGTH,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nomeFile, MAX_LENGTH_FILE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->voti))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Richiesta (XDR *xdrs, Richiesta *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->parametro, MAX_LENGTH,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->Titolo_Cantante))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Risultato (XDR *xdrs, Risultato *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->canzoni, MAX_SONGS,
		sizeof (Canzone), (xdrproc_t) xdr_Canzone))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->dim))
		 return FALSE;
	return TRUE;
}
