/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCXFILE_H_RPCGEN
#define _RPCXFILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_DIR 20
#define MAX_LENGTH 256
#define LENGTH 8
#define MAX_NUM_FILE 6

struct ListaStringhe {
	char nomefile[MAX_DIR];
};
typedef struct ListaStringhe ListaStringhe;

struct Richiesta {
	char nomeDir[MAX_DIR];
	char chr;
	int occorrenze;
};
typedef struct Richiesta Richiesta;

struct Risultato {
	ListaStringhe ls[MAX_NUM_FILE];
	int dim;
};
typedef struct Risultato Risultato;

#define OPERATION 0x20000013
#define OPERATIONVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define elimina_occorrenze 1
extern  int * elimina_occorrenze_1(char **, CLIENT *);
extern  int * elimina_occorrenze_1_svc(char **, struct svc_req *);
#define lista_file_carattere 2
extern  Risultato * lista_file_carattere_1(Richiesta *, CLIENT *);
extern  Risultato * lista_file_carattere_1_svc(Richiesta *, struct svc_req *);
extern int operation_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define elimina_occorrenze 1
extern  int * elimina_occorrenze_1();
extern  int * elimina_occorrenze_1_svc();
#define lista_file_carattere 2
extern  Risultato * lista_file_carattere_1();
extern  Risultato * lista_file_carattere_1_svc();
extern int operation_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_ListaStringhe (XDR *, ListaStringhe*);
extern  bool_t xdr_Richiesta (XDR *, Richiesta*);
extern  bool_t xdr_Risultato (XDR *, Risultato*);

#else /* K&R C */
extern bool_t xdr_ListaStringhe ();
extern bool_t xdr_Richiesta ();
extern bool_t xdr_Risultato ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCXFILE_H_RPCGEN */
