/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RPCxFile.h"

bool_t
xdr_ListaStringhe (XDR *xdrs, ListaStringhe *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nomefile, MAX_DIR,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Richiesta (XDR *xdrs, Richiesta *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nomeDir, MAX_DIR,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->chr))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->occorrenze))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Risultato (XDR *xdrs, Risultato *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->ls, MAX_NUM_FILE,
		sizeof (ListaStringhe), (xdrproc_t) xdr_ListaStringhe))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->dim))
		 return FALSE;
	return TRUE;
}
